'use client'
import React, { useState } from 'react'
import { Roboto } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false)

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        <main>
          <div className="p-4 sm:ml-64">{children}</div>
        </main>
      </body>
    </html>
  )
}
